

import PackageDescription

typealias _PackageDescription_Product = PackageDescription.Product
typealias _PackageDescription_Target = PackageDescription.Target
typealias _PackageDescription_TargetDependency = PackageDescription.Target.Dependency
typealias _PackageDescription_PackageDependency = PackageDescription.Package.Dependency
typealias _PackageDescription_SupportedPlatform = PackageDescription.SupportedPlatform
typealias LanguageTag = PackageDescription.LanguageTag
typealias Package = PackageDescription.Package

 
